### ISSUE TITLE
Redundant messages and (grammatically) Incorrect message while/after changing profile picture.

### ISSUE THREAD

**Issue by dineshmendhe1** [oaeproject/3akai-ux#4049] opened 2015-08-12 20:11 UTC
Following message get displayed after updating profile picture
![uploadprofile](https://cloud.githubusercontent.com/assets/10685804/9235463/d98f70ec-410c-11e5-9953-c6cc574a0ac9.jpg)
,
"Profile picture updated. The profile picture was successfully updated"

**Comment by mrvisser** [comment] 2015-08-13 11:33
Thanks for the report @dineshmendhe1. I see what you mean with the redundancy, though we do have a consistent pattern for these notifications that includes both a short header and a notification body.

I'm not exactly sure where there is a grammatical error, can you highlight it for me?

I'm going to mark this as requiring design feedback regarding the redundancy in the messaging.

**Comment by nicolaasmatthijs** [comment] 2015-08-13 13:59
I understand that there might be some unnecessary redundancy here, but as @mrvisser has pointed out, this is a consistent pattern across the application where the first part serves as the title and the second part serves as the description. As this is intended behaviour, I'm going to close this ticket.

**Closed by nicolaasmatthijs** 2015-08-13 13:59 UTC
Labels: Design required

**Comment by dineshmendhe1** [comment] 2015-08-13 14:02
Sure, Thank you so much.
