### ISSUE TITLE
The document which is created in a folder does not have the default visibility and permissions of the folder

### ISSUE THREAD

**Issue by shwetaarora3** [oaeproject/3akai-ux#3977] opened 2015-02-23 09:35 UTC
The document which is created in the folder does not have the default visibility and permissions of the folder.
- When you create a document in a GROUP it is automatically shared with the group and the creator of the document and so the document is visible in the library of the group.
- BUT When you create a document in a FOLDER, the folder is shared with the group, but the document is only shared with the document creator and hence the documents are not visible in the group's library.
- You are able to see the documents in the folder only because they are visible to you, not because they are shared with you.
- The comments appear in the group's activity feed because the folder containing the document is shared with the group.

**Comment by nicolaasmatthijs** [comment] 2015-02-26 16:44
@shwetaarora3 : Can you describe the bug in a bit more detail?

When I create a document inside of a folder, the document correctly receives the visibility of the folder as the default visibility. The people in the group are able to see the items in the folder because of the folder being shared with the group, which is also why the comments on the document will show up in the activity feed of the group.

**Comment by shwetaarora3** [comment] 2015-02-26 16:57
1) When you create a document inside of a folder, the document correctly receives the visibility of the folder as the default visibility. This is correct.
2) The people in the group are able to see the items in the folder because of the folder being shared with the group, which is also why the comments on the document will show up in the activity feed of the group. This is also correct.
BUT:
1) The documents in the folder (shared with the group) are not shared with the group by default. Should it not have the same sharing settings as that of the folder?
2) The document is only shared with the document creator and hence the documents are not visible in the group's library.

**Comment by nicolaasmatthijs** [comment] 2015-02-26 17:08
> 1) The documents in the folder (shared with the group) are not shared with the group by default. Should it not have the same sharing settings as that of the folder?

This is currently not the expected behaviour. A document can appear in multiple folders at the same time and those folders can be in multiple groups at the same time. We don't duplicate the sharing settings for a folder for each item that is being added to the folder, as that would make it hard to keep them in sync. Instead, the documents in the folder are essentially shared with all of the groups the folder is shared with through the virtue of the folder being shared with the group. Because of that, you can just add the folder to an additional group and the members of that group will automatically receive access to the content in the folder.

> 2) The document is only shared with the document creator and hence the documents are not visible in the group's library.

This is the current expected behaviour, which we arrived at through quite a bit of user feedback following the initial folders release. When people go through the effort of grouping their group content into folders, they didn't want to have a group library that still included all of those items individually.

**Comment by nicolaasmatthijs** [comment] 2015-02-26 17:13
@shwetaarora3 : Let me know if you have any further questions about this. I know permissions are a very complex area and it's almost impossible to get them right for all different usage scenarios.

In the meantime, I am going to close this ticket as the described behavior seems to be in line with the currently expected behavior. I will go ahead and incorporate this into our user feedback spreadsheet though. Do feel free to reopen this ticket if I misunderstood the issue.

**Closed by nicolaasmatthijs** 2015-02-26 17:13 UTC
Labels: Feedback Requested

**Comment by shwetaarora3** [comment] 2015-02-26 17:15
Thanks for the explanation. It now makes sense, as only then we can allow for a set of content items to be grouped into a folder without placing them in a specific location.
