### ISSUE TITLE
add group member widget (modal) freezes the browser

### ISSUE THREAD

**Issue by brunosmartin** [oaeproject/3akai-ux#4032] opened 2015-06-25 13:41 UTC
tested with Firefox (38.0.5) and Chrome (43.0.2357.130 (64-bit)), in demo enviroment (https://oae.oae-qa0.oaeproject.org).

In both cases, I wait for 2 minutes to get the browser back, and then I had to kill it.

My SO is an archlinux, with 8GB RAM and SSD, so, something seens  is wrong with javascrits... maybe a infinite loop?

**Comment by sathomas** [comment] 2015-06-25 13:44
Duplicate of https://github.com/oaeproject/3akai-ux/pull/4029

**Closed by sathomas** 2015-06-25 13:44 UTC
