### ISSUE TITLE
Print option on Etherpad not working

### ISSUE THREAD

**Issue by JoshBaron** [oaeproject/3akai-ux#4080] opened 2015-10-12 17:12 UTC
When you click on the "printer" icon in Etherpad/document it fails to created a PDF and does not allow you to print the content.  After about 2-4 minutes you get a "504 Gateway Time-out" error message.  Below the error message it reads "nginx/1.7.6"  The URL that was generated with the error message was: https://marist.oaeproject.org/etherpad/0/p/g.wp58jkJKmb8N4lH4$c_marist_4y5w2vi1x/export/pdf.  I'm on Windows 8 using Firefox 41.0.1.

I have noticed this issue in the past few months and had emailed Nico about it following one of the recent upgrades.  I noticed after emailing him that it was working again but just noticed the problem again.  FYI.

**Comment by nicolaasmatthijs** [comment] 2015-10-16 04:33
@simong : I know this issue has been present for a long time and there are significant issues with Etherpad's PDF export, but is there anything we can do to stabilize things a bit more (e.g. increase Nginx timeout for export endpoint)

**Comment by nicolaasmatthijs** [comment] 2015-10-16 04:33
Assigning to @simong for feedback

**Comment by simong** [comment] 2015-10-16 10:19
Increasing the timeout wouldn't help as Etherpad is simply failing to generate a PDF of the document. We could look into submitting a replacement for abiword (eg., libreoffice)

**Comment by JoshBaron** [comment] 2015-10-19 18:57
Although the feature was working as of this morning, I'm again encountering the same issue (timeout).  I hate to suggest this but if the option is not stable and encountering problems this often I'm wondering if we should keep the print button present?  Totally your call, just felt I had to ask the question.

**Comment by nicolaasmatthijs** [comment] 2015-10-20 03:47
@simong : Do you have a sense of how complicated it would be to hook up something like LibreOffice for the Etherpad exports?

**Comment by simong** [comment] 2015-10-20 19:13
I'm almost 100% sure that these bugs are due to AbiWord. We're on an older version, but upgrading is probably not going to be straightforward, there's no package readily available from apt and doing a manual install from source was tedious to say the least.

I wrote a LO convertor and [submitted a PR to etherpad](https://github.com/ether/etherpad-lite/pull/2813). Once that lands we can just use LO rather than abiword. It should be a bit more stable so hopefully 1 broken pad won't break all other exports.

**Comment by mrvisser** [comment] 2015-11-04 00:54
@JoshBaron I have deployed @simong 's fix to production, and we have done some regression testing in a bug bash to verify some of the issues such as intermittent timeouts have been resolved.

The document print functionality now uses the same technology that we use to covert word and other office processing documents to PDF, so we expect it to be as solid as that.

I'm going to resolve this ticket, but please feel free to re-open if you experience any issues.

**Closed by mrvisser** 2015-11-04 00:54 UTC
Labels: Feedback Requested
